
services:

  basedatos-mysql:
    image: mysql:8.0
    container_name: mysql_servidor_dockerorden
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: universidad_backend

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  pporden:
    image: misconcha/microservicio-pporden:v10-conchah
    container_name: api_pporden
    restart: always

    ports:
      - "8085:8085"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://basedatos-mysql:3306/universidad_backend
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      usuario.service.url: http://34.231.120.127:8081
      producto.service.url: http://34.231.120.127:8084
      evento.service.url: http://34.231.120.127:8082
      stands.service.url: http://34.231.120.127:8083
      notificacion.service.url: http://100.52.12.161:8090
      pagos.service.url: http://100.52.12.161:8087

    depends_on:
      - basedatos-mysql

volumes:
  mysql_data: